# Generated by Django 4.1 on 2024-03-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=100, unique=True, verbose_name='成果名')),
                ('achievement_date', models.DateField(null=True, verbose_name='取得时间')),
                ('ranking', models.PositiveIntegerField(null=True, verbose_name='排名')),
            ],
            options={
                'verbose_name': '项目成果信息',
                'verbose_name_plural': '项目成果信息',
                'db_table': 'Achievement',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名字')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='办公电话')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='移动电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '联系人信息',
                'verbose_name_plural': '联系人信息',
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100, unique=True, verbose_name='单位名称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('contacts', models.ManyToManyField(blank=True, related_name='organizations_as_contact_persons', to='app.contact', verbose_name='联系人')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_as_leader', to='app.contact', verbose_name='负责人')),
            ],
            options={
                'verbose_name': '单位信息',
                'verbose_name_plural': '单位信息',
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=100, unique=True, verbose_name='项目号')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名')),
                ('research_content', models.TextField(null=True, verbose_name='研究内容')),
                ('total_funding', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='经费总额(元)')),
                ('start_date', models.DateField(null=True, verbose_name='开工时间')),
                ('completion_date', models.DateField(null=True, verbose_name='完成时间')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_project', to='app.organization', verbose_name='唯一委托方')),
            ],
            options={
                'verbose_name': '科研项目信息',
                'verbose_name_plural': '科研项目信息',
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='RearchRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='研究室编号')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='研究室名称')),
                ('introduction', models.TextField(blank=True, db_column='introduction', max_length=19, null=True, verbose_name='研究方向介绍')),
                ('director_start_date', models.DateField(blank=True, null=True, verbose_name='主任_上任时间')),
                ('director_tenure', models.IntegerField(blank=True, null=True, verbose_name='主任_任期(年)')),
            ],
            options={
                'verbose_name': '研究室信息',
                'verbose_name_plural': '研究室信息',
                'db_table': 'researchRoom',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=12, verbose_name='工号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, null=True, verbose_name='性别')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='职称')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('research_area', models.CharField(max_length=200, null=True, verbose_name='研究方向')),
                ('research_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rearchrooms', verbose_name='所属研究室')),
            ],
            options={
                'verbose_name': '科研人员信息',
                'verbose_name_plural': '科研人员信息',
                'db_table': 'Researcher',
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('secretary_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=12, verbose_name='工号')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=10, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='聘用时间')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='职责')),
            ],
            options={
                'verbose_name': '秘书信息',
                'verbose_name_plural': '秘书信息',
                'db_table': 'secretary',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('userName', models.CharField(db_column='user_name', max_length=32, unique=True, verbose_name='用户账号')),
                ('passWord', models.CharField(db_column='pass_word', max_length=32, verbose_name='用户密码')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='用户性别')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('type', models.IntegerField(verbose_name='用户身份')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('subproject_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.DateField(blank=True, null=True, verbose_name='完成时间要求')),
                ('discretionary_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='支配经费')),
                ('tech_specification', models.TextField(blank=True, null=True, verbose_name='技术指标')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.researcher', verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '科研项目信息_子课题',
                'verbose_name_plural': '科研项目信息_子课题',
                'db_table': 'Subproject',
            },
        ),
        migrations.CreateModel(
            name='SoftwareCopyrights',
            fields=[
                ('copyright_id', models.AutoField(primary_key=True, serialize=False, verbose_name='著作权编号')),
                ('copyright_name', models.CharField(max_length=100, verbose_name='著作权名字')),
                ('other_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='详细信息')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='所属项目成果')),
            ],
            options={
                'verbose_name': '项目成果信息_软件著作权',
                'verbose_name_plural': '项目成果信息_软件著作权',
                'db_table': 'SoftwareCopyrights',
            },
        ),
        migrations.AddField(
            model_name='rearchrooms',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.researcher', verbose_name='主任'),
        ),
        migrations.AddField(
            model_name='rearchrooms',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.secretary', verbose_name='秘书'),
        ),
        migrations.CreateModel(
            name='ProjectResearcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='参加时间')),
                ('workload', models.FloatField(blank=True, null=True, verbose_name='工作量')),
                ('discretionary_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='可支配经费')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='所属项目')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.researcher', verbose_name='科研人员')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subproject', verbose_name='参与子课题编号')),
            ],
            options={
                'verbose_name': '科研项目信息_参与人员',
                'verbose_name_plural': '科研项目信息_参与人员',
                'unique_together': {('project', 'researcher')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'unique_together': {('project', 'collaborators')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(through='app.ProjectCollaborators', to='app.organization', verbose_name='合作方'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leading_projects', to='app.researcher'),
        ),
        migrations.AddField(
            model_name='project',
            name='qualityMonitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualityMonitor_project', to='app.organization', verbose_name='唯一监测方'),
        ),
        migrations.AddField(
            model_name='project',
            name='researcher',
            field=models.ManyToManyField(related_name='in_project', through='app.ProjectResearcher', to='app.researcher', verbose_name='参与人员'),
        ),
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('patent_id', models.AutoField(primary_key=True, serialize=False, verbose_name='专利编号')),
                ('patent_name', models.CharField(max_length=100, verbose_name='专利名字')),
                ('patent_type', models.CharField(blank=True, choices=[('发明', '发明'), ('实用新型', '实用新型'), ('外观', '外观')], max_length=100, null=True, verbose_name='专利类型')),
                ('other_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='详细信息')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='所属项目成果')),
            ],
            options={
                'verbose_name': '项目成果信息_专利',
                'verbose_name_plural': '项目成果信息_专利',
                'db_table': 'Patents',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='论文编号')),
                ('paper_name', models.CharField(max_length=100, verbose_name='论文题目')),
                ('paper_date', models.DateField(blank=True, null=True, verbose_name='取得时间')),
                ('other_paper_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='详细信息')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='所属项目成果')),
            ],
            options={
                'verbose_name': '项目成果信息_论文',
                'verbose_name_plural': '项目成果信息_论文',
                'db_table': 'Paper',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='办公场地编号')),
                ('office_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='办公面积(m²)')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('research_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rearchrooms', verbose_name='所属研究室')),
            ],
            options={
                'verbose_name': '办公场地信息',
                'verbose_name_plural': '办公场地信息',
                'db_table': 'office',
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, to='app.researcher', verbose_name='成果贡献人'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='所属项目'),
        ),
    ]
